### ISSUE TITLE
Package not working when using node

### ISSUE THREAD

**Issue by raster21** [cowprotocol/cow-sdk#36]
It seems that the bundle is not being exported in a way that it could be used with nodejs (with vanilla JS).
I found this pull request by @matextrem from the old/archived repo which fixes it: https://github.com/gnosis/cow-sdk/pull/14 but it was never merged into the main branch.

**Comment by alfetopito** [comment]
Thanks for digging it, we'll prioritize the fix internally (again) :)

**Comment by ramirotw** [comment]
hey @raster21 could you give more details about the error?

I did a quick test locally and it worked

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/3328006/174794662-56fc096e-3121-4b7e-87ce-4cd55b523eeb.png">

Here's the repo https://github.com/ramirotw/cow-sdk-nodejs

The https://github.com/gnosis/cow-sdk/pull/14 PR was a temp solution to replace microbundle but we finally fixed the problem in https://github.com/cowprotocol/cow-sdk/pull/6

**Comment by raster21** [comment]
@alfetopito @ramirotw thanks for having a look.

The issue appears when you try to use ES6-style `import` statements.

To reproduce the error, use: `import { CowSdk } from "@cowprotocol/cow-sdk";` and add `"type": "module"` to your `package.json` file.

The error:
> SyntaxError: Named export 'CowSdk' not found. The requested module '@cowprotocol/cow-sdk' is a CommonJS module, which may not support all module.exports as named exports.

This suggests that you're not including ES6-style modules that support `import` statements in the `cow-sdk` package.

**Comment by ramirotw** [comment]
hey @raster21 sorry for the late response!

I've prepared a [PR ](https://github.com/cowprotocol/cow-sdk/pull/51) with some changes to fix this issue. In the meantime while this is reviewed and published, I've also published a test package so you could try it and confirm everything works:

```bash
$ yarn add cow-sdk-test
```

Thanks!

**Comment by raster21** [comment]
@ramirotw it works, thanks! Waiting for v1.0.0-RC.1 to have a build so I can import it :-)

**Comment by ConjunctiveNormalForm** [comment]
I'm still not able to use this as a dependecy for a node typescript project. Problems seems to be missing type definitions:
```
Cannot find module 'utilities' or its corresponding type declarations.

 import { StrictUnion } from 'utilities';
```

0x/paraswap type definitions seem to also be missing, which can be fixed by adding
```
export * from '../api/cow/types'
export * from '../api/0x/types
```
to `src/types/index.ts`

I'm not a Node/typescript expert at all, so not sure if this has to do with setups etc. If it works for some setups, it'd be great to add a section in README with relevant examples/instructions.
